- README.md
Just updated some links that appeared to be wrong in the README.md
> Fixed some links in README

- LICENSE
- PREREQUISITES.md
- README.md
- app/index.js
- app/templates/_PREREQUISITES.md
- app/templates/_README.md
- app/templates/_package.json
- app/templates/app/_main.ts
- app/templates/app/components/files/_files.component.html
- app/templates/app/components/files/_files.component.ts
- app/templates/app/components/search/_search-bar.component.html
- app/templates/app/components/search/_search-bar.component.ts
- app/templates/app/components/search/_search.component.ts
- test/app.js
fix #4 
fix #5 
Update Readme 
Update License 
Fix search problem
Fix root buttons problem
> Dev eromano 0019

- CHANGELOG.md
- app/templates/_package.json
- package.json
fix npm run start fails on window
> npm run start fails on window machine #47

- app/templates/_tsconfig.json
> Update tsconfig.json for generated app

- app/index.js
- test/app.js
- allows viewing all available features at once and select the needed
- select all, inverse selection, single select
> feature selector

- app/templates/adf-cli-acs-aps-template/src/app/documentlist/documentlist.component.html
- app/templates/adf-cli-acs-aps-template/src/app/documentlist/documentlist.component.ts
- app/templates/adf-cli-acs-template/src/app/documentlist/documentlist.component.html
- app/templates/adf-cli-acs-template/src/app/documentlist/documentlist.component.ts
fix project templates
refs #2777
> fix overlay viewer in templates

- app/templates/adf-cli-acs-aps-template/.travis.yml
- app/templates/adf-cli-acs-aps-template/Dockerfile
- app/templates/adf-cli-acs-aps-template/README.md
- app/templates/adf-cli-acs-aps-template/docker.md
- app/templates/adf-cli-acs-aps-template/nginx.conf
- app/templates/adf-cli-acs-template/.travis.yml
- app/templates/adf-cli-acs-template/Dockerfile
- app/templates/adf-cli-acs-template/README.md
- app/templates/adf-cli-acs-template/docker.md
- app/templates/adf-cli-acs-template/nginx.conf
- app/templates/adf-cli-aps-template/.travis.yml
- app/templates/adf-cli-aps-template/Dockerfile
- app/templates/adf-cli-aps-template/README.md
- app/templates/adf-cli-aps-template/docker.md
- app/templates/adf-cli-aps-template/nginx.conf
Add the docker configuration file in the generated project
Add some documentation in the generator to explain how it works
Improve the travis file to deploy the docker image created
> [ADF-2164] Add docker support to the generated app

- .gitignore
- app/templates/adf-cli-acs-aps-template/package.json
- app/templates/adf-cli-acs-aps-template/src/app.config.json
- app/templates/adf-cli-acs-template/package.json
- app/templates/adf-cli-acs-template/src/app.config.json
- app/templates/adf-cli-aps-template/package.json
- app/templates/adf-cli-aps-template/src/app.config.json
See https://issues.alfresco.com/jira/browse/ADF-2249
> [ADF-2249] Adding schema validation

- .gitignore
- app/index.js
- app/templates/adf-cli-acs-aps-template/src/index.html
- app/templates/adf-cli-acs-template/src/index.html
- app/templates/adf-cli-aps-template/src/index.html
> [ADF-2293] loading spinner

- app/templates/adf-cli-acs-aps-template/src/app/app.module.ts
- app/templates/adf-cli-acs-template/src/app/app.module.ts
- app/templates/adf-cli-aps-template/src/app/app.module.ts
I have added BrowserAnimationsModule to help people with future use
> BrowserAnimationsModule add in modules

- app/templates/adf-cli-acs-aps-template/src/app/documentlist/documentlist.component.ts
- app/templates/adf-cli-acs-template/src/app/documentlist/documentlist.component.ts
> [no-issue] documentList fix viewchildren

- app/templates/adf-cli-acs-aps-template/src/app/documentlist/documentlist.component.html
- app/templates/adf-cli-acs-template/src/app/documentlist/documentlist.component.html
Add the spacer to the templates that use toolbars with buttons
> add spacer for the toolbars

- app/templates/adf-cli-acs-aps-template/angular.json
- app/templates/adf-cli-acs-template/angular.json
- app/templates/adf-cli-aps-template/angular.json
- matches the link in index.html
> Use provided favicon-96x96.png

- app/templates/adf-cli-acs-aps-template/angular.json
- app/templates/adf-cli-acs-aps-template/package.json
- app/templates/adf-cli-acs-aps-template/src/main.ts
- app/templates/adf-cli-acs-aps-template/src/polyfills.ts
- app/templates/adf-cli-acs-template/angular.json
- app/templates/adf-cli-acs-template/package.json
- app/templates/adf-cli-acs-template/src/main.ts
- app/templates/adf-cli-acs-template/src/polyfills.ts
- app/templates/adf-cli-aps-template/angular.json
- app/templates/adf-cli-aps-template/package.json
- app/templates/adf-cli-aps-template/src/main.ts
- app/templates/adf-cli-aps-template/src/polyfills.ts
fix issue with pdf.js
remove intl polyfill
remove web-animation polyfill
> fix blueprints

- app/templates/adf-cli-acs-aps-template/src/app/app.module.ts
- app/templates/adf-cli-acs-template/src/app/app.module.ts
- app/templates/adf-cli-aps-template/src/app/app.module.ts
> fix i18n provider setup

- README.md
- app/templates/adf-cli-activiti-acs-template/src/app.config.json
- app/templates/adf-cli-activiti-acs-template/src/app/apps/apps.component.ts
- app/templates/adf-cli-activiti-template/src/app.config.json
- app/templates/adf-cli-activiti-template/src/app/apps/apps.component.ts
- package.json
I have added the Activiti 7 app config.json to retrieve the a apps
> App list configuration activiti 7

- .travis.yml
- app/templates/adf-cli-activiti-acs-template/package.json
- app/templates/adf-cli-activiti-template/package.json
Update the template's names for the apps to name them after the recently introduced Activiti .
https://issues.alfresco.com/jira/browse/ADF-4217
> [ADF-4217] Update templates' names to Activiti

- app/templates/adf-cli-acs-aps-template/resources/i18n/ja.json
- app/templates/adf-cli-acs-template/resources/i18n/ja.json
- app/templates/adf-cli-activiti-acs-template/resources/i18n/ja.json
- app/templates/adf-cli-activiti-cloud-acs-template/resources/i18n/ja.json
- app/templates/adf-cli-activiti-cloud-template/resources/i18n/ja.json
- app/templates/adf-cli-activiti-template/resources/i18n/ja.json
- app/templates/adf-cli-aps-template/resources/i18n/ja.json
Hi.
Among the files under the i18n directory, there were other places where properties were missing.
How about it?
> Add missing i18n prop ja

- scripts/import-langs.sh
https://issues.alfresco.com/jira/browse/ADF-4866
Usage ./scripts/import-langs.sh -i ../i18n
1. Export languages from alfresco-ng2-components
2. Import them in the generator with the script
> [ADF-4866] Create script to import i18n files

- .travis.yml
Use previous last and next node version to test
> Update Node version test

- app/templates/adf-cli-acs-aps-template/src/app/app.module.ts
- app/templates/adf-cli-acs-template/src/app/app.module.ts
- app/templates/adf-cli-activiti-acs-template/src/app/app.module.ts
- app/templates/adf-cli-activiti-cloud-acs-template/src/app/app.module.ts
- app/templates/adf-cli-activiti-cloud-template/src/app/app.module.ts
- app/templates/adf-cli-activiti-template/src/app/app.module.ts
- app/templates/adf-cli-aps-template/src/app/app.module.ts
[ADF-5045](https://issues.alfresco.com/jira/browse/ADF-5045)
> [ADF-5045] Broken document list into a Yeoman generated ADF app	

- .gitignore
- .npmignore
- .travis.yml
- README.md
- docs/README.md
- docs/index.html
- scripts/git-tag.sh
- scripts/publish.sh
Move release task in travis build
> [AAE-1081] Add release task

- .travis.yml
Update travis variables with valid users for the different environments
> Update travis variables

- app/templates/adf-cli-acs-aps-template/angular.json
- app/templates/adf-cli-acs-template/angular.json
- app/templates/adf-cli-activiti-acs-template/angular.json
- app/templates/adf-cli-activiti-cloud-acs-template/angular.json
- app/templates/adf-cli-activiti-cloud-template/angular.json
- app/templates/adf-cli-activiti-template/angular.json
- app/templates/adf-cli-aps-template/angular.json
Fix common js warnings when application is started.
Add missing "aot" flag
> [ADF-5211] suppress commonjs warnings

- app/templates/adf-cli-acs-aps-template/src/app/documentlist/documentlist.component.html
- app/templates/adf-cli-acs-aps-template/src/app/file-view/file-view.component.html
- app/templates/adf-cli-acs-aps-template/src/app/file-view/file-view.component.scss
- app/templates/adf-cli-acs-aps-template/src/app/file-view/file-view.component.ts
- app/templates/adf-cli-acs-template/src/app/documentlist/documentlist.component.html
- app/templates/adf-cli-acs-template/src/app/file-view/file-view.component.html
- app/templates/adf-cli-acs-template/src/app/file-view/file-view.component.scss
- app/templates/adf-cli-acs-template/src/app/file-view/file-view.component.ts
- app/templates/adf-cli-activiti-acs-template/src/app/documentlist/documentlist.component.html
- app/templates/adf-cli-activiti-acs-template/src/app/file-view/file-view.component.html
- app/templates/adf-cli-activiti-acs-template/src/app/file-view/file-view.component.scss
- app/templates/adf-cli-activiti-acs-template/src/app/file-view/file-view.component.ts
- app/templates/adf-cli-activiti-cloud-acs-template/src/app/documentlist/documentlist.component.html
- app/templates/adf-cli-activiti-cloud-acs-template/src/app/file-view/file-view.component.html
- app/templates/adf-cli-activiti-cloud-acs-template/src/app/file-view/file-view.component.scss
- app/templates/adf-cli-activiti-cloud-acs-template/src/app/file-view/file-view.component.ts
- app/templates/adf-cli-activiti-cloud-template/src/app/file-view/file-view.component.html
- app/templates/adf-cli-activiti-cloud-template/src/app/file-view/file-view.component.scss
- app/templates/adf-cli-activiti-cloud-template/src/app/file-view/file-view.component.ts
- app/templates/adf-cli-activiti-template/src/app/file-view/file-view.component.html
- app/templates/adf-cli-activiti-template/src/app/file-view/file-view.component.ts
- app/templates/adf-cli-aps-template/src/app/file-view/file-view.component.html
- app/templates/adf-cli-aps-template/src/app/file-view/file-view.component.ts
Fix app freeze after closing viewer. 
https://alfresco.atlassian.net/browse/MNT-21924
https://alfresco.atlassian.net/browse/MNT-21925
> [MNT-21924] Fix Viewer freeze after closing.

- README.md
- Additional details on setting up the generator on multiple operating systems
- Polish the wording of the readme
> update the main readme with more info
